[package]
name = "unit-sim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.11"
bevy_ecs = "0.8.1"

[profile.dev]
opt-level = 1 

[profile.release]
opt-level = 3 
